export { HomePage } from './HomePage'
export { InnovationPage } from './InnovationPage'
export { ResearchPage } from './ResearchPage'
export { ProjectsPage } from './ProjectsPage'
export { StaffPage } from './StaffPage'
export { DirectorPage } from './DirectorPage'
export { PublicationsPage } from './PublicationsPage'
export { LocationPage } from './LocationPage'
export { ImpressumPage } from './ImpressumPage'
export { PrivacyPolicyPage } from './PrivacyPolicyPage'
export { TermsAndConditionsPage } from './TermsAndConditionsPage'
export { RefundPolicyPage } from './RefundPolicyPage'
export { ShippingPolicyPage } from './ShippingPolicyPage'

