backend:
  name: git-gateway
  branch: release-cms
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: 'Create {{collection}} "{{slug}}" {{authoringDate}}'

media_folder: 'public/uploads'
public_folder: '/uploads'

publish_mode: editorial_workflow

collections:
  - name: blogs
    label: Blogs
    folder: content/blogs
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'text', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              'Gender & Sexuality',
              'Migration & Asylum',
              'Comparative Law',
              'Equality & Non-Discrimination',
              'Legal Commentary',
              'Research Insights',
            ],
          required: false,
        }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - name: publications
    label: Publications
    folder: content/publications
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Link Label Text', name: 'label_text', widget: 'text', required: true }
      - { label: 'PDF URL', name: 'pdf_link', widget: 'string', required: false }
      - { label: 'PDF File Upload', name: 'pdf_file', widget: 'file', required: true }
      - { label: 'Category', name: 'category', widget: 'select', required: true, options:
          [
            'Comparative Legal Analysis',
            'Migration, Asylum & Transnational Law',
            'Law & Lived Experience',
            'Violence, Protection & Legal Gaps',
            'Policy & Commentary',
            'German Publications',
          ] }

  - name: newsletter
    label: Newsletter
    folder: content/newsletter
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Label Text', name: 'label_text', widget: 'text', required: true }
      - { label: 'Featured Image', name: 'featured_image', widget: 'image', required: true }
